name: Mobile Appium Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  android-tests:
    runs-on: self-hosted

    env:
      ANDROID_HOME: C:\Users\Dhiman Dasgupta\AppData\Local\Android\Sdk
      JAVA_HOME: C:\Program Files\Java\jdk-17
      UDID: emulator-5554

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Emulator
        shell: cmd
        run: |
          emulator -avd Pixel_4_API_30 -no-window -no-audio -gpu swiftshader_indirect
          adb wait-for-device

      - name: Start Appium Server
        shell: cmd
        run: |
          start cmd /k appium --base-path /wd/hub

      - name: Run Tests
        shell: cmd
        run: |
          mvn clean test -DsuiteXmlFile=testng.xml

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
